name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Copy built files to Backend
        run: |
          cp -r frontend/build/* backend/

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add backend/build/
          git commit -m "Update backend built files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: build
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Deploy from build branch
        run: |
          git checkout build
          railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
