name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Create backend/build directory if it doesn't exist
        run: mkdir -p backend/build 

      - name: Copy built files to Backend
        run: |
          cp -r frontend/build/* backend/build/

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add backend/build/
          git commit -m "Update backend built files"

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: backend # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Check if build branch exists
        run: |
          if git show-ref --verify --quiet "refs/heads/build"; then
            git checkout build
          else
            git checkout -b build
          fi
  

      - name: Deploy from build branch
        run: |
          git checkout build
          railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
